[project]
name = "crawler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.13",
    "parsel>=1.10.0",
    "pymongo>=4.13.2",
    "requests>=2.32.4",
]
